nvl_narrator "(CH2_1) 登山"

nvl_narrator "……"
nvl_narrator "距離登山隊出發已經幾個小時了，"
nvl_narrator "他們這次實地訓練預計當天就會回來。"
nvl_narrator "但我知道，"
nvl_narrator "最後只會有攝影師奧金能倖免於難。"

nvl_narrator "(CH2_2) 木屋"
nvl_narrator "(房間探索)"
nvl_narrator "密碼遊戲"
nvl_narrator "遊戲說明:根據線索，找出四位密碼鎖，一共有三次機會。"
nvl_narrator "線索:九宮格"
nvl_narrator "    "
nvl_narrator "密碼:8352"

nvl_narrator "通過:"
nvl_narrator "jump (CH2_3) 重逢"

nvl_narrator "未通過:"
nvl_narrator "(CH2_BE1) 奧金"
nvl_narrator "沒辦法，"
nvl_narrator "我無法離開木屋。"
nvl_narrator "只能繼續在房子裡待著，"
nvl_narrator "食物跟水都要吃完的時候，"
nvl_narrator "有人進來了屋子。"
nvl_narrator "……"
nvl_narrator "(END2)"

nvl_narrator "(CH2_3) 狂奔"
nvl_narrator "我打開了房門，"
nvl_narrator "離開木屋，"
nvl_narrator "開始朝著他們要攀登的厄爾布魯士峰跑去。"
nvl_narrator "踏入白茫茫的雪地，"
nvl_narrator "刺骨的寒風夾雜著冰渣打在我的身上，"
nvl_narrator "但我卻感覺不到冷。"
nvl_narrator "我循著記憶中熟悉的味道拼命向前跑。"
nvl_narrator "大約跑了 40 分鐘，周圍的環境突然發生了劇變。"
nvl_narrator "原本還能看見山腳下的木屋微弱的燈光，"
nvl_narrator "此刻卻被一陣突如其來的濃霧徹底覆蓋。"
nvl_narrator "能見度瞬間趨近於零，狂風在耳邊呼嘯。"

nvl_narrator "「汪/喵——！」我大聲呼喚著。"

nvl_narrator "就在不遠處的雪坡上，我看到了幾個模糊的身影。"
nvl_narrator "是他們！他們正在焦急地就地挖掘雪洞。"
nvl_narrator "主人聽到了我的叫聲，"
nvl_narrator "停下了手中的冰斧，"
nvl_narrator "滿臉震驚地看著我。"
nvl_narrator "「你怎麼會在這裡？！」他一把將我抱起，"
nvl_narrator "迅速塞進他厚實的羽絨服裡。"
nvl_narrator "雖然我不覺得冷，"
nvl_narrator "但感受到他胸膛傳來的急促心跳，"
nvl_narrator "我知道情況非常糟糕。"

nvl_narrator "挖掘的過程中，天空開始下起濕雪。"
nvl_narrator "當我們躲進剛挖好的雪洞時，"
nvl_narrator "夜幕已經降臨，"
nvl_narrator "山上的風速達到了驚人的每秒 30 米，"
nvl_narrator "濕度接近 100%。"
nvl_narrator "隊員們的羽絨服幾乎全濕透了，"
nvl_narrator "而在這種環境下，衣服根本無法乾透。"

nvl_narrator "(CH2_4) 雪洞"
nvl_narrator "(雪洞探索)"
nvl_narrator "我決定悄悄在狹小的洞穴裡巡視，看看大家都在做些什麼："
nvl_narrator "(menu) 1. 靠近 隊長列文 (Levin) "
nvl_narrator "**對話/觀察環節：**"
nvl_narrator "隊長列文眉頭緊鎖，拿著對講機。"
nvl_narrator "對講機裡傳來刺耳的雜音，"
nvl_narrator "山下的 11 號避難所似乎在詢問："
nvl_narrator "「是不是電池問題？請更換電池。」"
nvl_narrator "列文換了電池，但雜音依舊，"
nvl_narrator "他只能對著麥克風大喊："
nvl_narrator "「大雪導致了濕度問題，計畫明天下山！」"
nvl_narrator "晚上 20 點 30 分，通信徹底中斷了。"

nvl_narrator "我鑽到列文的腳邊。他眉頭深鎖，正死死握著那台不斷發出刺耳雜音的無線電。 他低聲喃喃自語：「這只是適應性訓練……不，我一定要把大家全部都安全帶下山。」 他的語氣中透著強烈的集體主義精神與不容妥協的沉重包袱。 我用爪子輕輕扒了一下他放在角落的背包，背包微微敞開，裡面傳來金屬碰撞的聲音。 我湊近一看，裡面竟然塞滿了大量的「冰鎬」！ 這起碼有幾十把（事後調查證實有 52 把），這完全不符合一般適應性訓練該有的裝備重量，似乎暗示著他們這趟上山還背負著某種不為人知的「秘密任務」。 這份沉甸甸的壓力，或許正是讓他日後在危機中屢屢「猶豫不決」的原因。"
nvl_narrator "2. 靠近 隊醫法布 (Fab) 我走向瀰漫著熟悉草藥味的法布。 作為擁有醫學博士學位的高手，他顯得相對沉穩。 他正蹲在地上，專注地調整著用來取暖的卡式爐與固體酒精。 我在他旁邊的醫療包裡，看到了一些沒有標籤的藥瓶。 他摸了摸我的頭，對旁邊的隊員輕聲說：「把這個吃下去，這能加快我們身體適應高原低氧的環境。」 這似乎是一種未知的「新藥」。 然而，他沒有察覺到，為了調節酒精燃燒而添加的「立德粉」，正在缺氧的環境下悄悄轉化為致命的氫氰酸氣體。 他身為技術最強悍的專家，卻為了照顧全隊而離毒氣源頭最近。"
nvl_narrator "3. 靠近 沃寧 (Voronin) 與 拉扎 (Raza) 這兩人縮在離洞口較近的位置，冷風時不時灌進來。 他們沒有像隊長那樣充滿大局觀，而是務實地檢查著身上的裝備。 拉扎用力擰著自己羽絨服上的雪水，低聲抱怨：「羽絨服最怕潮濕，這衣服根本不會乾了。」 沃寧眼神銳利地盯著被大雪封住的洞口，咬牙切齒地說：「如果天氣一放晴，我們必須馬上向山下求救，留在這裡跟等死沒兩樣！」 從他們的對話中，我感受到了一股極強的求生欲與現實判斷力。 他們已經對隊長讓所有人退回雪洞的決策感到不滿，隨時準備為了活下去而反抗權威。"
nvl_narrator "4. 靠近 奧金 (Ogin) 與 布爾金 (Burgin) 我走到奧金身邊，他正用敏銳的目光靜靜觀察著洞穴裡的每一個成員。 他手裡緊緊抱著相機，雖然無法拍照，但他似乎在腦海中記錄著這一切。 突然，坐在他旁邊的布爾金發出一陣急促的喘息聲，身體不自然地扭動著。 布爾金陷入了一種「奇怪的神經興奮狀態」，他不停地搓著手，甚至在極寒中說自己覺得有點熱。 奧金擔憂地扶住他，輕輕拍著他的背。 我聞到布爾金身上散發出一股奇怪的氣味，這似乎是吸入有毒氣體後神經系統開始紊亂的前兆，但他自己卻渾然不知。"
nvl_narrator "(menu end)"
nvl_narrator "當我巡視完一圈，深深感受到這不僅是一場與暴風雪的對抗，更是重壓、求生欲與隱藏秘密之間的定時炸彈。 所有人的命運，都將在接下來的幾個小時內迎來考驗……"
nvl_narrator "(CH2-4) 救援"

nvl_narrator "就在這時，洞外突然傳來微弱的動靜。"
nvl_narrator "我豎起耳朵，隊員們也警覺地拿起手電筒。"
nvl_narrator "雪洞外竟然有兩個人——是兩名全身濕透的日本登山客！"
nvl_narrator "隊長列文看著他們，正準備挪動身體讓他們進來。"
nvl_narrator "我決定_____:"
nvl_narrator "(menu) "
nvl_narrator "1. 保持安靜，讓他們進來"
nvl_narrator "隊長列文沒有猶豫，將他們讓進了雪洞。"
nvl_narrator "原本 6 個人的狹小空間，現在擠進了 8 個人（還有一隻我）。"
nvl_narrator "空氣逐漸變得稀薄，"
nvl_narrator "我也在不知不覺中睡去。 "
nvl_narrator "jump (CH3_1 下山)"
nvl_narrator "2. 凶狠地堵在洞口，不讓日本客進來(找到特定道具)"
nvl_narrator "我突然從主人的懷裡掙脫，"
nvl_narrator "衝到雪洞最外側的入口，"
nvl_narrator "對著那兩名日本客發出凶狠的低吼與咆哮。"
nvl_narrator "「汪汪汪！/ 嘶——！」 我露出尖牙，"
nvl_narrator "只要他們一靠近，我就作勢要咬上去。 "
nvl_narrator "主人錯愕地想把我拉回來："
nvl_narrator "「你在做什麼？快回來！」 "
nvl_narrator "但我死死卡在狹窄的洞口。 "
nvl_narrator "那兩名日本客本就處於嚴重的失溫與虛弱狀態，"
nvl_narrator "加上雙方語言不通，根本無法向列文求救。 "
nvl_narrator "看著一隻近乎發狂的動物堵住去路，"
nvl_narrator "他們眼裡閃過一絲絕望，"
nvl_narrator "最終只能互相攙扶著，"
nvl_narrator "轉身隱沒在狂風與濃霧之中。"
